Add set up instructions for pre commit hooks
coincoinche/coincoinche pull request #6
Opened 2019-09-20 18:44 UTC by Scrabouillmax

Set up autoformatting on pre-commit 🎉

2019-09-20 18:55 UTC, Scrabouillmax commented on src/test/java/com/coincoinche/CoincoincheApplicationTests.java
> +import static org.assertj.core.api.Assertions.assertThat;
This file change was done by the automated pre-commit formatting

2019-09-21 15:13 UTC, nockty requested changes
Could you double check the commands for the pre-commit hook? If I'm not mistaken, the hook automatically adds every `.java` file before committing. In my opinion, this shouldn't be recommended.

Maybe there is a way to create a script that only affects the files already staged for commit?

2019-09-21 15:13 UTC, nockty commented on README.md
> +`git add $(git ls-files|grep \.java$)`
Does this mean all `.java` files will be added automatically right before committing? Are we sure we want to recommend this practice?
For instance, say I'm working on two very different features in `FeatureOne.java` and `FeatureTwo.java`. Wouldn't I want to have two distinct commits for them?

2019-09-21 15:13 UTC, nockty commented on README.md
> +`git add $(git ls-files|grep \.java$)`
This could also cause issues if we have some local file that we don't want to commit, `LocalMainJustForTests.java`.

2019-09-27 08:42 UTC, nockty approved these changes

2019-09-27 08:44 UTC, merged